### ISSUE TITLE
doesnt bypasses anything

### ISSUE THREAD

**Issue by JacqueSatan** [zkcm1337/Discord-rate-limit-bypass#2]
its in the title

**Comment by zkcm1337** [comment]
duplicate of #1 i suggest you to read it.

**Comment by JacqueSatan** [comment]
discord.js "bypasses" the rate limit automatically then

**Comment by zkcm1337** [comment]
you will still get rate limited if you to many events at a certain time for eg dmall

**Comment by JacqueSatan** [comment]
well your method is very inefficient, you should just catch the rate limit exception and make your program wait for the given amount of time

**Comment by zkcm1337** [comment]
its a simple code, you can modify it however you want, im not making everything from front to back because people need to figure somethings out them selfs
